name: WIN build
on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    name: Windows
    env:
      CMSIS: CMSIS_5
    runs-on: windows-2019
    steps:
    - name: ARM GCC setup
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: 8-2019-q3
    - name: Checkout
      uses: actions/checkout@v2
    - name: Resolve prerequisites
      run: make cmsis SHELL=cmd
    - name: testbuild F103
      run: make stm32f103x6 SHELL=cmd
    - name: testbuild F303
      run: make stm32f303xe SHELL=cmd
    - name: testbuild F105
      run: make stm32f105xb SHELL=cmd
    - name: testbuild L052
      run: make stm32l052x8 SHELL=cmd
    - name: testbuild L100
      run: make stm32l100xc SHELL=cmd
    - name: testbuild L476
      run: make stm32l476xg SHELL=cmd
    - name: testbuild F429
      run: make stm32f429xi SHELL=cmd
    - name: testbuild L433
      run: make stm32l433cc SHELL=cmd
    - name: testbuild F070
      run: make stm32f070xb SHELL=cmd
    - name: testbuild G431
      run: make stm32g431xb SHELL=cmd
    - name: testbuild F446
      run: make stm32f446xc SHELL=cmd
    - name: testbuild F373
      run: make stm32f373xc SHELL=cmd
    - name: testbuild F745
      run: make stm32f745xe SHELL=cmd
